name: Test Actions

on:
  push:
    branches: [master, dev]
  pull_request:
    branches: [master]
    paths:
      - 'setup-*/**'

jobs:
  flutter:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - uses: ./setup-android
        with:
          accept-licenses: 'y'
          packages: >-
            platform-tools
            tools
            emulator
            build-tools;30.0.3
            patcher;v4
            platforms;android-31

      - uses: ./setup-flutter
        with:
          flutter-version: '3.0'

      - name: Test
        run: |-
          flutter create app
          cd app && flutter build appbundle